<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy-Intro" data-toc-modified-id="NumPy-Intro-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy Intro</a></span></li><li><span><a href="#Arrays" data-toc-modified-id="Arrays-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Arrays</a></span><ul class="toc-item"><li><span><a href="#Math" data-toc-modified-id="Math-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Math</a></span><ul class="toc-item"><li><span><a href="#Remember-Lists?" data-toc-modified-id="Remember-Lists?-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Remember Lists?</a></span></li><li><span><a href="#Looking-at-NumPy-Arrays" data-toc-modified-id="Looking-at-NumPy-Arrays-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>Looking at NumPy Arrays</a></span></li></ul></li><li><span><a href="#Multidimensional" data-toc-modified-id="Multidimensional-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Multidimensional</a></span></li><li><span><a href="#Using-some-built-ins" data-toc-modified-id="Using-some-built-ins-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Using some built-ins</a></span></li><li><span><a href="#Slicing-&amp;-Dicing" data-toc-modified-id="Slicing-&amp;-Dicing-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Slicing &amp; Dicing</a></span></li></ul></li></ul></div>

![NumPy logo](images/NumPy_logo.png)

# NumPy Intro

In [1]:
# Usually imported as `np`
import numpy as np

# For later
import pandas as pd

# Arrays

Arrays are very similar to lists but do have some extra efficiency and actions

For a little more detail on this, check out this section from _Python Data Science Handbook_: [Understanding Data Types in Python](https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html#A-Python-Integer-Is-More-Than-Just-an-Integer)

In [2]:
# Let's define an array!
my_arr = np.array([1,2,3,4])
my_arr

array([1, 2, 3, 4])

In [3]:
# We can create numpy arrays in lots of different ways
use_range = range(10)
print('Using range: ', np.array(use_range))

use_tuple = (5,2,3)
print('Using tuples: ', np.array(use_tuple))

use_series = pd.Series([1,2,3])
print('Using pd.Series: ', np.array(use_series))

Using range:  [0 1 2 3 4 5 6 7 8 9]
Using tuples:  [5 2 3]
Using pd.Series:  [1 2 3]


## Math

### Remember Lists?
A certain syntax

In [4]:
list0 = [1,2,3]
list0

[1, 2, 3]

In [5]:
list0 + 4

TypeError: can only concatenate list (not "int") to list

In [6]:
list0 + [4]

[1, 2, 3, 4]

What about multiplication?

In [7]:
print(list0 * 3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


What about division?

In [8]:
print(list0 / 3)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

Adding lists together; what's going to happen?

In [9]:
list0 = [0,1,2]
list1 = [3,4,5]
print(list0)
print(list1)
print(list0 + list1)

[0, 1, 2]
[3, 4, 5]
[0, 1, 2, 3, 4, 5]


### Looking at NumPy Arrays

In [10]:
np_arr0 = np.array(range(4))
np_arr0

array([0, 1, 2, 3])

In [11]:
# All them math
print(np_arr0 + 3)
print(np_arr0 - 3)
print(np_arr0 * 3)
print(np_arr0 / 3)

[3 4 5 6]
[-3 -2 -1  0]
[0 3 6 9]
[0.         0.33333333 0.66666667 1.        ]


In [12]:
# Adding arrays together
np_arr0 = np.array([0,1,2])
np_arr1 = np.array([3,4,5])
print(np_arr0)
print(np_arr1)
print(np_arr0 + np_arr1)

[0 1 2]
[3 4 5]
[3 5 7]


## Multidimensional

In [13]:
arr_2d = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
])

print(arr_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
arr_3d = np.array([
    [range(0,3),range(3,6),range(6,9)],
    [range(9,12),range(12,15),range(15,18)],
    [range(18,21),range(21,24),range(24,27)]
])

print(arr_3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [15]:
print(arr_2d.shape)
print(arr_3d.shape)

(3, 3)
(3, 3, 3)


## Using some built-ins

In [16]:
#3 dimensional; 3 4x5 matrices
zeros_3d = np.zeros([3,4,5])
print(zeros_3d)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [17]:
#3 dimensional; 3 4x5 matrices
ones_3d = np.ones([3,4,5])
print(ones_3d)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [18]:
#3 dimensional; 3 4x5 matrices
full_3d = np.full([3,4,5], 27)
print(full_3d)

[[[27 27 27 27 27]
  [27 27 27 27 27]
  [27 27 27 27 27]
  [27 27 27 27 27]]

 [[27 27 27 27 27]
  [27 27 27 27 27]
  [27 27 27 27 27]
  [27 27 27 27 27]]

 [[27 27 27 27 27]
  [27 27 27 27 27]
  [27 27 27 27 27]
  [27 27 27 27 27]]]


In [19]:
# Note we can do some fun stuff with full
np.full(5, range(5))

array([0, 1, 2, 3, 4])

In [20]:
# But this won't work  with multi-dim :(
np.full([5,2], range(10))

ValueError: could not broadcast input array from shape (10) into shape (5,2)

## Slicing & Dicing

We can slice NumPy arrays but they differ from Python's lists

In [21]:
arr0 = np.random.randint(low=0, high=10, size=[5,8])
arr0

array([[8, 2, 8, 2, 3, 5, 5, 7],
       [8, 0, 6, 8, 2, 0, 6, 3],
       [5, 9, 3, 6, 0, 5, 3, 9],
       [9, 3, 6, 0, 9, 1, 7, 3],
       [8, 5, 5, 3, 7, 1, 7, 5]])

In [22]:
# Getting rows
print('first row', arr0[0])
print('last row', arr0[-1])
print('multiple rows\n', arr0[1:3])

first row [8 2 8 2 3 5 5 7]
last row [8 5 5 3 7 1 7 5]
multiple rows
 [[8 0 6 8 2 0 6 3]
 [5 9 3 6 0 5 3 9]]


In [23]:
# Selecting sub-arrays
row_start, row_end = 2, 7
col_start, col_end = 3, 6

print(
    arr0[
        row_start:row_end,
        col_start:col_end
    ]
)

[[6 0 5]
 [0 9 1]
 [3 7 1]]
